### ISSUE TITLE
Instructions in README for LAshow need to update

### ISSUE THREAD

**Issue by cancan101** [thegenemyers/DALIGNER#10]
See: https://github.com/thegenemyers/DALIGNER/blob/8edd180ba7b5302c6f1fc859eef5c646db99fd87/README#L321

Should likely be:
```bash
LAshow -c -a -w50 G G.1 | more
```

**Comment by thegenemyers** [comment]
Amended to "LAshow G G | more", the -c, -a, and -w50 would not lead to 
the output
shown.  Thanks,  Gene
