### ISSUE TITLE
seg fault daligner

### ISSUE THREAD

**Issue by macmanes** [thegenemyers/DALIGNER#12]
Working with Nanopore dataset.

     daligner -M10 -d lambda.1 lambda.1

database seems fine: 

    >more lambda.db
    files =         1
       1131 lambda.pp m000000_000000_00000_c1898213712391273
    blocks =         1
    size =        50 cutoff =         0 all = 0
         0         0
      1131      1131

gdb stack trace

    ...
     1127 vs  1130 : 906   1082.. x   187..  -895 (2550)  [  900, 6362] x [    0, 5432] = 1518
                       6607.. x  5725..  -882 (2550)  [ 6528, 9031] x [ 5645, 8132] =  679
                       9380.. x  8489..  -891 (2550)  [ 9353,11909] x [ 8462,10953] =  690
                      12134.. x 11183..  -951 (2550)  No alignment 66

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff71f29bc in __GI___libc_free (mem=0x7fffffffd880) at malloc.c:2945
    2945	malloc.c: No such file or directory.

dmesg

    daligner[21243]: segfault at 7fffa0000000 ip 00007fb3bea5b9bc sp 00007fffa24bfbf8 error 4 in libc-2.19.so[7fb3be9d8000+1bb000

What else can I send you to help debug?

**Comment by pb-jchin** [comment]
it is probably more proper to ask Jared Simpson to solve this problem and submit a patch if he can find any issue in my opinion.  his github site: https://github.com/jts

**Comment by jts** [comment]
I will look into this as soon as I can.
