### ISSUE TITLE
munmap_chunk(): invalid pointer: 0x00007fff77201010 

### ISSUE THREAD

**Issue by fbemm** [thegenemyers/DALIGNER#13]
We are trying to align two smaller genomes (160Mb) to each other:

*** glibc detected *** /ebio/abt6/fbemm/software/dazzler/daligner/daligner: munmap_chunk(): invalid pointer: 0x00007fff77201010 ***
[Thread 0x7fff03ae2700 (LWP 22826) exited]
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7de16)[0x7ffff757fe16]
/ebio/abt6/fbemm/software/dazzler/daligner/daligner[0x40510c]
/ebio/abt6/fbemm/software/dazzler/daligner/daligner[0x40529f]
/ebio/abt6/fbemm/software/dazzler/daligner/daligner[0x4028ec]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7ffff752376d]
/ebio/abt6/fbemm/software/dazzler/daligner/daligner[0x401349]
======= Memory map: ========
00400000-00422000 r-xp 00000000 00:15 1275101                            /ebio/abt6/fbemm/software/dazzler/daligner/daligner
00622000-00623000 rw-p 00022000 00:15 1275101                            /ebio/abt6/fbemm/software/dazzler/daligner/daligner
00623000-00647000 rw-p 00000000 00:00 0                                  [heap]
7fff030cb000-7fff030e1000 r-xp 00000000 00:15 9477371                    /ebio/abt6/fbemm/software/gcc-4.9.1_sub/lib64/libgcc_s.so.1
7fff030e1000-7fff032e0000 ---p 00016000 00:15 9477371                    /ebio/abt6/fbemm/software/gcc-4.9.1_sub/lib64/libgcc_s.so.1
7fff032e0000-7fff032e1000 rw-p 00015000 00:15 9477371                    /ebio/abt6/fbemm/software/gcc-4.9.1_sub/lib64/libgcc_s.so.1
7fff032e1000-7fff032e2000 rw-p 00000000 00:00 0 
7fff032e2000-7fff032e3000 ---p 00000000 00:00 0 
7fff032e3000-7fff03ae3000 rw-p 00000000 00:00 0 
7fff03ae3000-7fff03ae4000 ---p 00000000 00:00 0 
7fff03ae4000-7fff042e4000 rw-p 00000000 00:00 0 
7fff042e4000-7fff042e5000 ---p 00000000 00:00 0 
7fff042e5000-7fff04ae5000 rw-p 00000000 00:00 0 
7fff04ae5000-7fff04ae6000 ---p 00000000 00:00 0 
7fff04ae6000-7ffff7502000 rw-p 00000000 00:00 0 
7ffff7502000-7ffff76b6000 r-xp 00000000 fc:00 628450                     /lib/x86_64-linux-gnu/libc-2.15.so
7ffff76b6000-7ffff78b6000 ---p 001b4000 fc:00 628450                     /lib/x86_64-linux-gnu/libc-2.15.so
7ffff78b6000-7ffff78ba000 r--p 001b4000 fc:00 628450                     /lib/x86_64-linux-gnu/libc-2.15.so
7ffff78ba000-7ffff78bc000 rw-p 001b8000 fc:00 628450                     /lib/x86_64-linux-gnu/libc-2.15.so
7ffff78bc000-7ffff78c1000 rw-p 00000000 00:00 0 
7ffff78c1000-7ffff79bc000 r-xp 00000000 fc:00 628460                     /lib/x86_64-linux-gnu/libm-2.15.so
7ffff79bc000-7ffff7bbb000 ---p 000fb000 fc:00 628460                     /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7bbb000-7ffff7bbc000 r--p 000fa000 fc:00 628460                     /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7bbc000-7ffff7bbd000 rw-p 000fb000 fc:00 628460                     /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7bbd000-7ffff7bd5000 r-xp 00000000 fc:00 628451                     /lib/x86_64-linux-gnu/libpthread-2.15.so
7ffff7bd5000-7ffff7dd4000 ---p 00018000 fc:00 628451                     /lib/x86_64-linux-gnu/libpthread-2.15.so
7ffff7dd4000-7ffff7dd5000 r--p 00017000 fc:00 628451                     /lib/x86_64-linux-gnu/libpthread-2.15.so
7ffff7dd5000-7ffff7dd6000 rw-p 00018000 fc:00 628451                     /lib/x86_64-linux-gnu/libpthread-2.15.so
7ffff7dd6000-7ffff7dda000 rw-p 00000000 00:00 0 
7ffff7dda000-7ffff7dfc000 r-xp 00000000 fc:00 628459                     /lib/x86_64-linux-gnu/ld-2.15.so
7ffff7fc1000-7ffff7fe6000 rw-p 00000000 00:00 0 
7ffff7ff9000-7ffff7ffb000 rw-p 00000000 00:00 0 
7ffff7ffb000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00022000 fc:00 628459                     /lib/x86_64-linux-gnu/ld-2.15.so
7ffff7ffd000-7ffff7fff000 rw-p 00023000 fc:00 628459                     /lib/x86_64-linux-gnu/ld-2.15.so
7ffffffdd000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

gdb stack trace:

Program received signal SIGABRT, Aborted.
0x00007ffff75380d5 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Happens also if target/subject only contain a single large sequence (1Mb).

**Comment by thegenemyers** [comment]
Send me the small datasets that cause a crash and the exact command you 
uttered that
caused the crash. -- I can't debug from a stack trace.
    Cheers,
        Gene
