### ISSUE TITLE
No alignments reported when using DALIGNER as a mapper

### ISSUE THREAD

**Issue by boyko-** [thegenemyers/DALIGNER#15]
I am not getting any alignments when using DALIGNER as a mapper.  It works great when I align PacBio reads among themselves, but when I try to align them to a DAM built from the human reference sequence (hg38.fasta), I get the output below.  The output of DBstats on both (dusted) databases, looks reasonable in both the number of contigs and their length distribution. I also tried mapping the reads to a smaller smaller portion of hg38 (chr1), and also tried to map chr1.dam to itself but had the same (lack of) results.

```
############# DALIGNER OUTPUT ##############

$ daligner -vbA -M60 $READS.dam hg38.dam

Building index for 030915_HK_run_42246_9

Kmer count = 704,510,721
Using 21.00Gb of space
Index occupies 10.41Gb

Building index for c(030915_HK_run_42246_9)

Kmer count = 704,510,721
Using 21.00Gb of space
Index occupies 10.39Gb

Building index for hg38

Comparing c(030915_HK_run_42246_9) to hg38

0 14-mers (0.000000e+00 of matrix)
0 seed hits (0.000000e+00 of matrix)
0 confirmed hits (0.000000e+00 of matrix)

Building index for hg38

Comparing 030915_HK_run_42246_9 to hg38

0 14-mers (0.000000e+00 of matrix)
0 seed hits (0.000000e+00 of matrix)
0 confirmed hits (0.000000e+00 of matrix)
```

**Comment by thegenemyers** [comment]
The .dam's must be broken into blocks less than 2billion chars long.
