### ISSUE TITLE
How to find out where the read loss in the db building phase comes from?

### ISSUE THREAD

**Issue by chklopp** [thegenemyers/DALIGNER#17]
Hi,

When I run a DBstats on the raw_reads.db, the results shows quiet a lot of lost reads 

DBstats raw_reads.db
Statistics for all wells in the data set

1,655,303 reads       out of       4,099,447    59.6% loss
13,561,952,097 base pairs out of 24,496,694,744 44.6% loss

How can I get the reasons and the corresponding reads?

**Comment by thegenemyers** [comment]
Hmmmm, by default DBstats reports on one read per well, if you have lots of short reads
that got read multiple times in each well, then that could explain your numbers -- try the
-a option.
