### ISSUE TITLE
Please tag a stable release

### ISSUE THREAD

**Issue by sjackman** [thegenemyers/DALIGNER#2]
Thanks!

**Comment by sjackman** [comment]
It would be helpful to tag a stable release. It's easier to refer to version `0.1.0` than it is to refer to version `d4aa4871122b35ac92e2cc13d9b1b1e9c5b5dc5c`.

**Comment by thegenemyers** [comment]
I've created V1.0 for all 3 modules.  Good idea and I'll use the tags 
from now on.
Sorry, I'm not very sophisticated at using Github.
    -- Gene

**Comment by sjackman** [comment]
Fantastic! Thanks, Gene. I've updated the version of DALIGNER in Homebrew-science: https://github.com/Homebrew/homebrew-science/pull/2492
