### ISSUE TITLE
Error: "Block ... contains reads < 20bp long! Run DBsplit."

### ISSUE THREAD

**Issue by haghshenas** [thegenemyers/DALIGNER#21]
Hi,

I have been trying to map some simulate pacbio reads (from PBSIM) to the human reference genome hg19. I tried to run commands as it is advised on the website and readme files.

For the reference genome:
```
$ fasta2DAM ref hg19.fasta
$ DBsplit ref
$ DBdust ref.1
...
$ DBdust ref.14
```
and for the read:
```
$ fasta2DB read read.fasta
$ DBsplit read
$ DBdust read.1
```
Then, I ran HPCmapper to get the commands:
```
$ HPCmapper ref.dam read.db
```
Among the daligner commands generated by HPCmapper, the second command gives error (the first one works without any problem):
```
$ daligner -A -k20 -h50 -e.85 ref.2 read.1
daligner: Block ref.2 contains reads < 20bp long !  Run DBsplit.
```
But I have already used DBsplit both for the reference genome and the reads. Could you give more information about this error and how I can resolve it?

Thanks!

**Comment by thegenemyers** [comment]
I believe the "problem" is that there are some very small "contigs" 
(<20bp) interspersed
bewteen N's in hg19.fasta.  Call "DBsplit -x100 ref" before applying the 
mapper and I think
all all should then be fine.
    -- Gene

**Comment by haghshenas** [comment]
That helped. daligner works now.

Thank you.
