### ISSUE TITLE
daligner crash

### ISSUE THREAD

**Issue by dgordon562** [thegenemyers/DALIGNER#22]
This is the daligner that is part of  v0.3.3 Falcon.  

With a particular pair of files it gives (see below).

Let me know what other information I can provide you...

.
.
.
Building index for raw_reads.193

   Kmer count = 399,655,782
   Using 11.91Gb of space
   Revised kmer count = 334,780,204
   Index occupies 4.99Gb

Comparing c(raw_reads.545) to raw_reads.193

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 997,361,227
   Highwater of 39.67Gb space
*** glibc detected *** daligner: free(): invalid pointer: 0x00002bb67c0008c0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x37b6c75e66]
daligner[0x4097a2]
daligner[0x406f1d]
daligner[0x402817]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x37b6c1ed5d]
daligner[0x401339]
======= Memory map: ========
00400000-00421000 r-xp 00000000 00:36 3895273357                         /net/gs/vol1/home/dg
ordon/falcon150714/FALCON-integrate/DALIGNER/daligner
00620000-00621000 rw-p 00020000 00:36 3895273357                         /net/gs/vol1/home/dg
ordon/falcon150714/FALCON-integrate/DALIGNER/daligner
00621000-00624000 rw-p 00000000 00:00 0 
01d80000-01dd9000 rw-p 00000000 00:00 0                                  [heap]
37b6800000-37b6820000 r-xp 00000000 fd:00 41418757                       /lib64/ld-2.12.so
37b6a1f000-37b6a20000 r--p 0001f000 fd:00 41418757                       /lib64/ld-2.12.so
37b6a20000-37b6a21000 rw-p 00020000 fd:00 41418757                       /lib64/ld-2.12.so
37b6a21000-37b6a22000 rw-p 00000000 00:00 0 
.
.
.

**Comment by pb-jchin** [comment]
@dgordon562 you will need to give @thegenemyers  some example data, otherwise it is probably very hard to see what is going on. I suggest trying to use "-M" option to see if you can push the job through.

**Comment by thegenemyers** [comment]
Sorry for the very late reply.

Are you running on a 40Gb+ memory machine?  Looks like it ran out
of memory and then did not exit gracefully.  If that is not the problem
then I would like to know the exact code line on which it died -- you can
get this by compiling the the -g flag instead of the -O3, run with gdb or
lldb and ask for a backtrace.  That or I need the input which seems like
a non-starter given its size.

    Cheers,
         Gene

**Comment by dgordon562** [comment]
Hi, Gene,

Yes, the computer has 180GB of RAM.  I will get you a backtrace.

Best wishes,
David
