### ISSUE TITLE
change align.c Base bias back to warning

### ISSUE THREAD

**Issue by klabutti** [thegenemyers/DALIGNER#23]
Hello,

The latest version of align.c exits if it encounters a base bias worse than 80/20%.  Previous versions used a warning.  To make Falcon assembly with data exhibiting such biases possible it may be more beneficial to warn rather than exit.
Thanks,
Kurt

# current version exits with message:
	  if (match < .2)
    { EPRINTF(EPLACE,"Base bias worse than 80/20%% ! (New_Align_Spec)\n");
      free(spec);
      EXIT(NULL);
    }

# previous version would just warn with message:
 if (match < .2)
    { fprintf(stderr,"Warning: Base bias worse than 80/20%% !\n");
      bias = 3;
    }

**Comment by thegenemyers** [comment]
I've shifted it back, it no longer exits, but it does cap the bias model at 80/20.
