### ISSUE TITLE
little suggestion regarding installation

### ISSUE THREAD

**Issue by ebioman** [thegenemyers/DALIGNER#40]
Hello
I am just in the middle of installing your software on a cluster and packaging RPMs.
In the middle of it I realized that I encountered an error as your makefile specifies for the installation 
always ``~/bin``. Obviously this is easy to overcome by changing the makefile. But could you please support in a next release common installation variables such as DESTDIR ?
Cheers

**Comment by thegenemyers** [comment]
Done.  Committed to main branch.
   -- Gene

**Comment by ebioman** [comment]
Great, thanks a lot.
Cheers
