### ISSUE TITLE
No inter-block alignments in .las files

### ISSUE THREAD

**Issue by arthurmelobio** [thegenemyers/DALIGNER#41]
Hi Dazz Team,

In trying to assemble a ~900MB diploid plant genome using a ~120x dataset of PacBio reads, we are finding that well under 1% of our reads are passing from HPCdaligner to Falcon as corrected preads.  Scanning the .las files from the pre-assembly, we observe that there are local alignment hits only when a block from the database is aligned with itself.  For example, if the raw read DB was split into five different blocks, creating these 6 daligner jobs:

```
# Daligner jobs (6)
daligner -v -k18 -h50 -t18 -H18600 -e0.75 -l2500 -M4 1SMRT.1 1SMRT.1
daligner -v -k18 -h50 -t18 -H18600 -e0.75 -l2500 -M4 1SMRT.2 1SMRT.1 1SMRT.2
daligner -v -k18 -h50 -t18 -H18600 -e0.75 -l2500 -M4 1SMRT.3 1SMRT.1 1SMRT.2 1SMRT.3
daligner -v -k18 -h50 -t18 -H18600 -e0.75 -l2500 -M4 1SMRT.4 1SMRT.1 1SMRT.2 1SMRT.3 1SMRT.4
daligner -v -k18 -h50 -t18 -H18600 -e0.75 -l2500 -M4 1SMRT.5 1SMRT.1 1SMRT.2
daligner -v -k18 -h50 -t18 -H18600 -e0.75 -l2500 -M4 1SMRT.5 1SMRT.3 1SMRT.4 1SMRT.5
```

...what we find is that hits occur only within blocks, as indicated below in the list of produced files (note 12K = empty file):

```
 1.5M   1SMRT.1.1SMRT.1.C0.las
 1.5M   1SMRT.1.1SMRT.1.C1.las
 1.2M   1SMRT.1.1SMRT.1.C2.las
 1.4M   1SMRT.1.1SMRT.1.C3.las
 2.0M   1SMRT.1.1SMRT.1.N0.las
 1.8M   1SMRT.1.1SMRT.1.N1.las
 1.6M   1SMRT.1.1SMRT.1.N2.las
 1.7M   1SMRT.1.1SMRT.1.N3.las
   12k  1SMRT.1.1SMRT.2.C0.las
   12k  1SMRT.1.1SMRT.2.C1.las
   12k  1SMRT.1.1SMRT.2.C2.las
   12k  1SMRT.1.1SMRT.2.C3.las
   12k  1SMRT.1.1SMRT.2.N0.las
   12k  1SMRT.1.1SMRT.2.N1.las
   12k  1SMRT.1.1SMRT.2.N2.las
   12k  1SMRT.1.1SMRT.2.N3.las
   12k  1SMRT.1.1SMRT.3.C0.las
   12k  1SMRT.1.1SMRT.3.C1.las
   12k  1SMRT.1.1SMRT.3.C2.las
   12k  1SMRT.1.1SMRT.3.C3.las
   12k  1SMRT.1.1SMRT.3.N0.las
   12k  1SMRT.1.1SMRT.3.N1.las
   12k  1SMRT.1.1SMRT.3.N2.las
...
 1.5M   1SMRT.2.1SMRT.2.C0.las
 1.5M   1SMRT.2.1SMRT.2.C1.las
 1.4M   1SMRT.2.1SMRT.2.C2.las
 1.3M   1SMRT.2.1SMRT.2.C3.las
 2.0M   1SMRT.2.1SMRT.2.N0.las
 1.9M   1SMRT.2.1SMRT.2.N1.las
 1.7M   1SMRT.2.1SMRT.2.N2.las
 1.8M   1SMRT.2.1SMRT.2.N3.las
   12k  1SMRT.2.1SMRT.3.C0.las
   12k  1SMRT.2.1SMRT.3.C1.las
   12k  1SMRT.2.1SMRT.3.C2.las
   12k  1SMRT.2.1SMRT.3.C3.las
   12k  1SMRT.2.1SMRT.3.N0.las
   12k  1SMRT.2.1SMRT.3.N1.las
   12k  1SMRT.2.1SMRT.3.N2.las
   12k  1SMRT.2.1SMRT.3.N3.las
   12k  1SMRT.2.1SMRT.4.C0.las
   12k  1SMRT.2.1SMRT.4.C1.las
   12k  1SMRT.2.1SMRT.4.C2.las
   12k  1SMRT.2.1SMRT.4.C3.las
   12k  1SMRT.2.1SMRT.4.N0.las
   12k  1SMRT.2.1SMRT.4.N1.las
   12k  1SMRT.2.1SMRT.4.N2.las
   12k  1SMRT.2.1SMRT.4.N3.las
...
 1.7M   1SMRT.3.1SMRT.3.C0.las
 1.7M   1SMRT.3.1SMRT.3.C1.las
 1.6M   1SMRT.3.1SMRT.3.C2.las
 1.5M   1SMRT.3.1SMRT.3.C3.las
 2.2M   1SMRT.3.1SMRT.3.N0.las
 2.0M   1SMRT.3.1SMRT.3.N1.las
 2.0M   1SMRT.3.1SMRT.3.N2.las
 2.0M   1SMRT.3.1SMRT.3.N3.las
   12k  1SMRT.3.1SMRT.4.C0.las
   12k  1SMRT.3.1SMRT.4.C1.las
   12k  1SMRT.3.1SMRT.4.C2.las
   12k  1SMRT.3.1SMRT.4.C3.las
   12k  1SMRT.3.1SMRT.4.N0.las
   12k  1SMRT.3.1SMRT.4.N1.las
   12k  1SMRT.3.1SMRT.4.N2.las
   12k  1SMRT.3.1SMRT.4.N3.las
   12k  1SMRT.3.1SMRT.5.C0.las
   12k  1SMRT.3.1SMRT.5.C1.las
   12k  1SMRT.3.1SMRT.5.C2.las
   12k  1SMRT.3.1SMRT.5.C3.las
   12k  1SMRT.3.1SMRT.5.N0.las
   12k  1SMRT.3.1SMRT.5.N1.las
   12k  1SMRT.3.1SMRT.5.N2.las
   12k  1SMRT.3.1SMRT.5.N3.las
...
```

We have systematically adjusted HPCdaligner parameters like -l, -k, -t, -h and -s; but the pattern is robust.

Our questions:
1. Is this exclusive alignment of reads within the same block expected? 
2. What parameter adjustment would you suggest to increase alignments across blocks?
3. If we could obtain cross-block alignments, do you think it would result in more reads being available for the OLC assembly?

Thank you so much for your time,
Arthur Melo

For your reference:

Starting with this base HPCdaligner parameterization:

```
HPCdaligner -v -dal4 -e0.75 -M4 -l2500 -k18 -t18 -h50 -s500 -H18600
```

We have adjusted the following flags through the ranges specified, with no success in generating inter-block alignments:
-k  (14-32)
-t  (18-56)
-h  (50-1250)
-s  (100-500)

**Comment by thegenemyers** [comment]
Why do you set -H to 18600?  That is the HGAP asymmetry parameter and implies that only
reads over 18,600 will have hits reported to them.  That has to be a mistake.  I'd start there.
   -- Gene

**Comment by arthurmelobio** [comment]
Hi Gene, thank you for your answer. 
The -H 18600 is our 30x threshold (the longest top 30x based on read lenght distribution). It was set that way under advice by the PacBio team. Do you think even 18600 is the 30x threshold we need to change this value?

Thank you
