### ISSUE TITLE
Kmer setting in daligner 

### ISSUE THREAD

**Issue by spiderman0327** [thegenemyers/DALIGNER#44]
Dear experts:

```
    I am do de novo assemble recently of PacBio data using Falcon program, it seems that kmer settings is an important parameter for assemble, but I cannot find any parameters for setting kmer in daligner. But   -t is a parameter to cap the kmer amount, it is confusing for me. Looking forward to your reply. Thank you. 
```

**Comment by thegenemyers** [comment]
The parameter is -k:

Usage: daligner [-vbAI] [-k<int(14)>] [-w<int(6)>] [-h<int(35)>] 
[-t<int>] [-M<int>]
                         [-e<double(.70)] [-l<int(1000)>] [-s<int(100)>] 
[-H<int>] [-T<int(4)>]
                         [-m<track>]+ <subject:db|dam> <target:db|dam> ...

   -- Gene
