### ISSUE TITLE
HPC.daligner keep printing LAcheck

### ISSUE THREAD

**Issue by mke135** [thegenemyers/DALIGNER#46]
Dear,
I want to use DALIGNER to map raw reads of a dataset to the contigs produced by some assembler. 
Firstly, I convert the raw data into DB by fasta2DB and contigs into DAM. The statistics of this dataset:
![1](https://cloud.githubusercontent.com/assets/19401977/17010120/9eb97d24-4f33-11e6-98e7-a9e13805fa4b.png)
The statistics of the contigs:
![2](https://cloud.githubusercontent.com/assets/19401977/17010138/cd895dc2-4f33-11e6-82f4-a39dbd65a335.png)
But when I run :
./HPC.daligner -k15 -h50 -e.7 data.db contig.dam >r2c.sh
The program would not stop and kept printing “LAcheck -vS contig data”such like that (C : contig.dam, E: data.db):
![2016-07-21 11 15 53](https://cloud.githubusercontent.com/assets/19401977/17010221/89b64a5a-4f34-11e6-9ea3-a03f37340575.png)
I don’t know why about that. And I try to run:
/HPC.daligner -k15 -h50 -e.7 data.db >r2r.sh
The program run successfully and produced corresponding file (a 418M file).
Hence, I thought there was some problem in the contig.dam, and I replaced it with the contig dam file of other dataset, or data db file of other dataset. But this problem still existed (keep printing “LAcheck -vS contig data”). 
Then, I don't know why it happens (looks like that there is a dead loop).

**Comment by thegenemyers** [comment]
Thanks Mike and very sorry, my fault, I introduced this bug recently.
It was an easy fix, and is now been committed to the latest version of
the trunk.  If you grab a new copy of HPC.daligner.c from github all
will hopefully be good.
    -- Gene

**Comment by mke135** [comment]
Thank you very much for your timely reply!
I downloaded the new version of DALIGNER and it produced unix shell script to compare reads with contigs successfully.
And I compare the code produced by the previous version (read to read alignment) with the new version. For the steps before "Level 1 merge jobs" are almost the same. I want to confirm if the previous version produced correct unix shell script for the program.

**Comment by thegenemyers** [comment]
Yes, the code was only blown for the reads vs contigs case, the read 2 
read subroutine
generated the correct code and did not need fixing (I checked).
    -- Gene

**Comment by mke135** [comment]
Thanks. I am closing this issue.
