### ISSUE TITLE
LAdump: not all trace-points

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DALIGNER#51]
It seems that `LAdump -t` shows the trace-points for the first alignment only.

In fact, `LAdump -cd` shows all alignements, but `LAdump -cdt` shows only the first.

E.g.
```
+ P 3
% P 1
+ T 564
% T 258
@ T 258
P 92772 92773 c .
C 5464 18218 0 12802
T 129
...
```
Even though it says `P3`, there are no other sections. And we see only `129` trace-points in the dump, not `564`.

Can you verify that?

**Comment by thegenemyers** [comment]
I reviewed the code for LAdump.  Saw a couple of hinky things in there, 
but none that
explained your phenomena.  Did clean it up a bit anyway.

Just checked in a version of DALIGNER module where LAmerge uses memmove, 
daligner
now will error exit if the /tmp file area overflows, and with the slight 
cleanup of LAdump
just in case it does fix the problem (although I think not).

If the problem still persists, please send me the data set.  Looks small 
with only 3 overlaps
in it.

    -- Gene
