### ISSUE TITLE
Identify (-I) flag in HPC.daligner

### ISSUE THREAD

**Issue by gt1** [thegenemyers/DALIGNER#53]
daligner has the -I flag for computing alignments between a read and itself. This flag is missing in HPC.daligner. I think it would be useful to have it in HPC.daligner as well.

**Comment by thegenemyers** [comment]
It was there but I took it out once I generalized HPC.daligner to do a 
data set against itself, and to
do a data set against another.  I think of HPC.daligner as a script 
generator for these instances, in
which case -I doesn't make sense.

-I is really only useful if you are looking for tandems or internal 
structure.  HPC.tandem does that
better.

    -- Gene
