### ISSUE TITLE
Add option for read length output to 'LAshow' and 'LAdump'

### ISSUE THREAD

**Issue by DDDolle** [thegenemyers/DALIGNER#56]
Hi,

would it be possible to add a command line parameter to 'LAshow' and 'LAdump' so that it also outputs the length of the reads involved in a given overlap?

Currently I can get the overlaps from the LAS files with 'LAdump' and the read length from the DB using 'DBdump' but then I have to match them up myself. As both 'LAshow' and 'LAdump' use the DB as input anyway it would be neat to have the possibility to also output the read length. This would allow to bypass some of the scripts of the FALCON-intergrate tool set and generate the *.ovlp files needed for assembly directly using only DAZZLER tools.

Thanks,

 Dirk

**Comment by thegenemyers** [comment]
I've added the requested features.  The latest version of LAshow always output the length of the two reads in the first line, and LAdump now has a -l option which causes a 'L' line with the two read lengths to be output upon request.
