### ISSUE TITLE
HPC.daligner -d option cleanup

### ISSUE THREAD

**Issue by gt1** [thegenemyers/DALIGNER#59]
Using the -d option of HPC.daligner the program outputs a section containing sequences like

cd dir
rm files
cd ..

which is not consistent with the semantics that every line of a section can be executed in parallel to get the same result as when running the lines sequentially.

I would suggest to replace this by

cd dir ; rm files ; cd ..

**Comment by thegenemyers** [comment]
I assumed one would never execute that section on the cluster, but 
rather serially on the
file server.  But you are right in that in so doing I abandoned a 
property I had asserted in
the documentation.  So I changed it as per your suggestion, so the 
property remains true.
   Thanks,
       Gene
