### ISSUE TITLE
Removing repeats before assembly

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DALIGNER#60]
Dear Dr. Myers,
Where could I find your software to identify  "_Repeats before Assembly_" which you talked about in "_Is Perfect Assembly Perfect?_"?

Thank you in advance.

Michal

**Comment by thegenemyers** [comment]
Google "Dazzler Blog" to get to my website about my assembly work. In the
menu bar click "Commands" and select the "DAMASKER module".  From there
you will find a link to Github in the first paragraph that will take you 
to the
code.  Of if you want to go direct without any background:

    https://github.com/thegenemyers/DAMASKER

    Cheers,  Gene

**Comment by mictadlo** [comment]
Thank you
