### ISSUE TITLE
align SMRT cells against a reference

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DALIGNER#61]
Hi,
How Is it possible to align RSII and Sequel SMRT cells against a reference genome and received mapped and unmapped reads?

Thank you in advance.

Michal

**Comment by thegenemyers** [comment]
Use the DAMAPPER module.  The link to the blog post is here

https://dazzlerblog.wordpress.com/2016/07/31/damapper-mapping-your-reads/
