### ISSUE TITLE
Still Getting Duplicated Regions Error

### ISSUE THREAD

**Issue by BioWu** [thegenemyers/DALIGNER#62]
I used daligner in FALCON pipeline, and I had updated to the newest version. But in the LACheck steps, I still melt this error. I tried to solve it by masking the LACheck steps. But, I did not know if there might be several unknown mistakes. And, how could I avoid this.

Thanks.

**Comment by thegenemyers** [comment]
The problem is "benign" and I have not had anyone give me a manageable data set
with which I can reproduce the problem.  If you can, I'd be happy to look at it.
   Best,  Gene
