### ISSUE TITLE
Add meson build system

### ISSUE THREAD

**Issue by SoapZA** [thegenemyers/DALIGNER#65]
Hi @thegenemyers,
Meson is a new meta-buildsystem that generates Ninja files instead of Makefiles. It is much faster, allows for greater portability and has many nice features such as building as part of other projects, enabling address/memory/undefined-behaviour sanitiser and unity builds. Would you be willing to accept a PR to add it?

**Comment by thegenemyers** [comment]
Hi David,

    I'd rather not incorporate it into my main branch as I don't use it 
and don't want to
learn it which I would have to do as new codes are added to modules 
going forward.
But I have no problem with your keeping an update branch as things go along.

      Cheers,  Gene

**Comment by SoapGentoo** [comment]
@thegenemyers 
would the `update` branch live in the main repo or in a forked one?

**Comment by thegenemyers** [comment]
Would prefer you fork.  -- Gene
