### ISSUE TITLE
genome with 30%GC content

### ISSUE THREAD

**Issue by hermeseduardo** [thegenemyers/DALIGNER#66]
Hi there,

I am assembling a genome with 30%GC content, using Falcon, 40X coverage. You mentioned that some option made ('If the -b option is set'), alert daligner of a compositional bias, so I just add this option in my pa and ovlp fc_run.cfg, right?

Eg:
pa_HPCdaligner_option =  -vb -B70 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -vb -B70 -t32 -h60 -e.96 -l500 -s1000

**Comment by thegenemyers** [comment]
I took it out (the -b option) as it didn't seem to help.  At 70% AT it 
should still be OK albeit long
stretches of A and T only can create some bad alignments, but only in a 
handful of place in our
experience with Mediterranus Schmidtae which has a similar compositional 
bias.

    -- Gene

**Comment by hermeseduardo** [comment]
thanks. Looks like I am working with an old version then since the -b option it is still there. I think that it is interesting since bias composition could be a big deal in the assembly, specially if the PacBio coverage is low, in my case 40X. I will have a go with -b just to see what happens but then will update to the latest version. 
Because of the low coverage I am also playing with other daligner options, eg. -e. , if you can think of any suggestion it will be appreciated, specially when the long reads gets split because of low coverage. I will asses the assembly later with two libraries of Illumina (80X)
