### ISSUE TITLE
Mutual containment

### ISSUE THREAD

**Issue by gt1** [thegenemyers/DALIGNER#69]
Hello Gene,

I see the following as an output of daligner/LAshow:

 1   2 n   [    1..8,696> x <    0..8,990>  ~  23.00%   (8,990 x 8,696 bps,2,034 diffs, 87 trace pts)
 2   1 n   <    0..8,990> x [    1..8,696>  ~  23.00%   (8,696 x 8,990 bps,2,034 diffs, 90 trace pts)

I wonder if this worked as intended. I thought daligner would try to extend alignments to the end of a read (in this case both) if it was close to an end, even if that meant lowering the score by that extension.

Best,
German

**Comment by thegenemyers** [comment]
Yes, this is strange -- it should have extended to the end.  Any chance
you can send me .fasta's of the two reads?
    -- Gene
