### ISSUE TITLE
daligner: Track 'dust' annotation file is junk

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DALIGNER#73]
Hi,

I got many `daligner: Track 'dust' annotation file is junk` with the following commands

```
DBsplit -x500 -s200 DB
DBdust DB 
HPC.daligner DB -T8 -mdust -H6973 
```

I wrote the following script to submit each command from `test.01.OVL` parallel.

```
#!/bin/bash

while IFS='' read -r line || [[ -n "$line" ]]; do
  cmd=$line 

  #cat <<EOF
  qsub <<EOF
#!/bin/bash -l

#PBS -N HPCdaligner
#PBS -l walltime=48:00:00
#PBS -j oe
#PBS -l mem=80G
#PBS -l ncpus=4
#PBS -M m.lorenc@qut.edu.au
###PBS -m bea

cd \$PBS_O_WORKDIR

$cmd

EOF

done < "$1"
```

The script gets executed as following way `sh HPC.daligner_pbs.sh test.01.OVL` 

Did I miss anything?

Thank you in advance.

Michal

**Comment by thegenemyers** [comment]
Hmm, I ran exactly your sequence on a small E.Coli data base and did not
encounter a problem.  Your more recent issue e-mail about the daligner 
itself
suggests you got passed this issue, please advise?  (And if you did 
figure out
what the problem is could you let me know.)
    -- Gene

**Comment by mictadlo** [comment]
I think I forgotten to do `Catrack -v DB dust`
