### ISSUE TITLE
DB2Falcon and LA4Falcon

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DALIGNER#75]
Hi,
Where can I find `DB2Falcon` and `LA4Falcon` for the new daligner version?

Thank you in advance,

Michal

**Comment by thegenemyers** [comment]
Don't know -- not software I wrote :-)  -- Gene

**Comment by mictadlo** [comment]
Hi, there were part of this Daligner [release](https://codeload.github.com/thegenemyers/DALIGNER/tar.gz/9a56b8d03caf1511c8ab32209c77a7cbf41f11ae) .

**Comment by thegenemyers** [comment]
Pressing your link initiates a download so I don't know where the 
release is on
Github or who made it.  I can only assert that I have never built such 
tools.  It
is most likely you are downloading something made by Pacbio's software
developers.
    -- Gene

**Comment by mictadlo** [comment]
Hi Gene,
`DB2falcon` it appears to be just a different name to `DB2fasta`.

According to the comments inside `LA4Falcon` it is
```
Based on the original LAshow.c, this code is modified by Jason Chin to support generating
 consensus sequences from daligner output
```
Would you be able to add this new feature to your `LAshow.c` code?

Thank you in advance. 

Michal
