### ISSUE TITLE
malloc error in daligner

### ISSUE THREAD

**Issue by dyermd** [thegenemyers/DALIGNER#8]
Operating System: OSX

Dataset: PacBio example dataset - http://datasets.pacb.com.s3.amazonaws.com/2014/c_elegans/40X/raw_data/2590970/0001/Analysis_Results/m140928_184123_42139_c100719602550000001823155305141590_s1_p0.1.bax.h5

Process:
dextract -v -omatt/data m140928_184123_42139_c100719602550000001823155305141590_s1_p0.1.bax.h5
fasta2DB matt/database matt/data.fasta
quiva2DB matt/database matt/data.quiva
DBsplit matt/database
HPCdaligner -d -t2 matt/database | csh -v

Error:
 6899 vs  6901 :   3
 6899 vs  6970 :   3
 6901 vs  6902 :   3
 6901 vs  6912 :   3
 6901 vs  6930 :   3
 6908 vs  6933 :   3
 6911 vs  6976 :   3
 6913 vs  6918 :   3
 6915 vs  6951 :   3
 6917 vs  6955 :   5
 6918 vs  6962 :   3
 6919 vs  6971 :   3
 6920 vs  6980 :   3
 6921 vs  6970 :   3
 6946 vs  6951 :   3
 6951 vs  6970 :   3
 6953 vs  6975 :   3
daligner(10634,0x7fff732db300) malloc: *** error for object 0x8859: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort

LAsort database.1.database.1.C0 database.1.database.1.N0 database.1.database.1.C1 database.1.database.1.N1 database.1.database.1.C2 database.1.database.1.N2 database.1.database.1.C3 database.1.database.1.N3 && LAmerge database.1 database.1.database.1.C0.S database.1.database.1.N0.S database.1.database.1.C1.S database.1.database.1.N1.S database.1.database.1.C2.S database.1.database.1.N2.S database.1.database.1.C3.S database.1.database.1.N3.S && rm database.1.database.1.C0.S.las database.1.database.1.N0.S.las database.1.database.1.C1.S.las database.1.database.1.N1.S.las database.1.database.1.C2.S.las database.1.database.1.N2.S.las database.1.database.1.C3.S.las database.1.database.1.N3.S.las

Other Question:
Once this step completes how do I perform the de novo assembly piece? I couldn't find any dazzler executable.

**Comment by thegenemyers** [comment]
Hmmm, I pulled out the data, repeated exactly your steps and all ran fine.

Could you try again, save compile with -g instead of -O3 and run in lldb 
or gdb
debugger, and give me a stack trace of where exactly the crash occurred?

This could just be a simple matter of a bad free call near the end of 
execution,
that somehow I screwed up (albeit not sure how at this point in the 
development
cycle).

    -- Gene

**Comment by dyermd** [comment]
Thanks Gene. If I decrease the chunk size it appears to work fine. Let me
know if you still want me to dig into this.

On Tue, Mar 24, 2015 at 4:56 AM, Eugene W Myers Jr <notifications@github.com
