### ISSUE TITLE
Output trace point spacing (`-s`) in `LAdump`

### ISSUE THREAD

**Issue by a-ludi** [thegenemyers/DALIGNER#89]
I am using the trace points in my program but `LAdump` does not output the trace point spacing therefore I have to "guess", e.i. the user has to supply a non-default value manually. This is prone to errors and makes the user interface more complex than necessary. So I propose to output the value in the dump either (1) as an additional header line or (2) as an additional column of `T` lines.

**Comment by thegenemyers** [comment]
Actually, it does.  There is a line X # that occurs once in the header, 
where # is the trace
spacing.
    -- Gene

**Comment by a-ludi** [comment]
Oh, that's very cool. I did not realize because it was a rather [recent change](https://github.com/thegenemyers/DALIGNER/commit/30bb40a8b40261b6d1d3d44dac377703ef7f8a35#diff-5c8edcc93df2174d902c5856777f9e2fR389).
