### ISSUE TITLE
HPCplanner in README should say HPCdaligner

### ISSUE THREAD

**Issue by cancan101** [thegenemyers/DALIGNER#9]
see: https://github.com/thegenemyers/DALIGNER/blob/8edd180ba7b5302c6f1fc859eef5c646db99fd87/README#L307

**Comment by thegenemyers** [comment]
Yes, thanks.  Failed to update this when I changed the name a long time ago.
Will be correct in next minor update.
    -- Gene

**Comment by thegenemyers** [comment]
Done
